### ISSUE TITLE
New eBay UI is unsupported

### ISSUE THREAD

**Issue by will-gant** [Makeshift/Hide-Collection-Only-eBay#2] opened 2023-03-11 10:21 UTC
Hi there. First of all, thanks very much for the extension, which has found me a bunch of bargains in the past :-)

I believe the extension has stopped working since a redesign of eBay's UI that was presumably deployed to production at some point since your last release six months ago. This is my first attempt to use the extension since then.

## What I did:

As I want a swanky new office chair, earlier today I [searched](https://www.ebay.co.uk/sch/i.html?_from=R40&_nkw=herman+miller+aeron&_sacat=0&LH_ItemCondition=2500%7C3000&LH_BIN=1&rt=nc&LH_FS=1&_stpos=N1%203HB&_fcid=3) for "herman miller aeron" on ebay.co.uk

My setup:
* macOS Ventura 13.1 (22C65)
* A clean install of Chrome Version 111.0.5563.64 (Official Build) (x86_64) with default settings
* The 'Hide Collection-Only Button for eBay' extension version 1.2.4 with default settings

I also tried this with Brave - a Chromium-based browser that previously worked with this extension. The Brave version was 1.48.171 Chromium: 110.0.5481.177 (Official Build) (x86_64).

## What happened:

<img width="1570" alt="Screenshot 2023-03-11 at 10 03 02" src="https://user-images.githubusercontent.com/20523607/224478281-4382e021-0475-4f3b-ab77-68daed3ad94b.png">

## What I expected to happen:

A `Hide Collection-Only` button should have appeared somewhere around the dropdown menu buttons above the list of results.

Thanks!

**Comment by Makeshift** [comment] 2023-06-18 14:47
Hey will, apologies for the late response (apparently my github emails were being marked as spam - thanks gmail) and thank you for the bug report.

You're not the only one to have reported this, but unfortunately I'm not able to replicate it as the redesign doesn't appear to have been pushed to everyone yet.

I've tried several browsers and machines, and in all cases I get the same layout, where the addon appears to work fine, including on the link you provided:
![image](https://github.com/Makeshift/Hide-Collection-Only-eBay/assets/345013/7f3f9bc6-8c7a-4fda-844f-0b772bf6bc6a)

Do you have any ideas how I could forcibly enable the new layout?

**Comment by Makeshift** [comment] 2023-07-01 13:35
If anybody else comes across this issue (I've linked it on the Chrome extension page) and would be willing to help me support the new UI, I'd appreciate it!

The most useful support would be a method that allows me to enable the new UI. I may also be able to work with a saved version of the page (ctrl+s, zip it up and add it to a comment here), but in that case I'd likely have to send a development build of the extension to someone with the new UI to test, as I'd be developing blind.

Any other help is appreciated.

Cheers :)

**Comment by will-gant** [comment] 2023-09-27 08:12
@Makeshift My turn to be slow replying - apologies! Strangely, using the exact same extension version (1.2.4) I now no longer get this issue:

![Screenshot 2023-09-27 at 08 52 21](https://github.com/Makeshift/Hide-Collection-Only-eBay/assets/20523607/6a197235-0392-43c3-92bb-192a29412be9)

I've had a good rummage through my account settings, but unfortunately I've got no idea how to choose which version of the UI to use (or even how to know which version I'm _currently_ using). It's quite possible that they don't expose that setting, and just pick some percentage of users to unwittingly 'test' it for them. Am now kicking myself for not getting a copy of the source when I had the chance!

Anyway, happy I can now easily find bulky stuff to order again (at least for now!) :-)

**Comment by will-gant** [comment] 2023-09-27 08:36
Ok this isn't the same thing, and I'd guess it's a feature you hadn't prioritised rather than a bug, but I've just spotted that the button also doesn't appear when browsing as opposed to searching (e.g. [here](https://www.ebay.co.uk/b/Dining-Sets/36032?Number%2520of%2520Place%2520Settings=8&rt=nc))

<img width="2032" alt="Screenshot 2023-09-27 at 09 22 19" src="https://github.com/Makeshift/Hide-Collection-Only-eBay/assets/20523607/37b8c4cf-41e1-42c2-8536-fc47cdf7ebad">

In case this is a thing you actually do expect to work, and also turns out to be awkward to reproduce, I've saved a copy of the source in [a gist](https://gist.github.com/will-gant/502f42fcbd206f879da73fb6c10280a0) for you.

**Comment by Makeshift** [comment] 2023-11-08 14:41
> I've just spotted that the button also doesn't appear when browsing as opposed to searching (e.g. [here](https://www.ebay.co.uk/b/Dining-Sets/36032?Number%2520of%2520Place%2520Settings=8&rt=nc))

I think you may have hit the nail on the head there! I've never used 'browse' on eBay and so hadn't seen this layout, how incredibly weird that they use a different one, but only for this view.

Thank you for the reproducible example, I'll see if I can make it work.

**Comment by Makeshift** [comment] 2023-11-08 20:28
I've just uploaded [1.3.0](https://github.com/Makeshift/Hide-Collection-Only-eBay/releases/tag/v1.3.0) and it's awaiting review on both the Chrome and Firefox extension stores. It now appears to work in both the browse and search views, although I'm not particularly happy with how I had to find collection-only items in the browse view, as I have to search for the text specifically. In the search view there's a specific class for collection-only so it's relatively easy, but in the browse view they use the same class for all delivery options.

Even so, hopefully should be working shortly! Please let me know if anything is broken.

**Comment by will-gant** [comment] 2023-11-09 13:08
Legend! Can't wait :)

**Comment by Makeshift** [comment] 2023-11-10 11:10
Should be pushed out and working now. I really appreciate your help with this one, it's been bugging me for a long time that it appeared to work for some and not others, and I had no idea there was two separate result view screens!

I'm leaving this reference list of things here in case something like this comes up again, mainly to jog my memory:
- The extension will only activate on `/sch/` and `/b/` pages, which is quite restrictive but I saw no need to extend the list
- On `/b/` pages it'll likely break if the language isn't English, because we have to look for the 'Collection-only' text specifically. I attempted to translate them into the locales but I'm not particularly happy with the solution (On `/b/`, ebay uses the same class name for all delivery options, so it's not as simple as the `/sch/` pages)
- Again on `/b/` pages, it'll almost certainly break if the users browser language and ebay language differ.

A slightly nicer solution may be to go through all the ebay languages manually and grab the text string that represents collection-only, and just look for all of them when on `/b/` pages. Considering that 98% of my users (according to the Chrome store, anyway) are English though, I may avoid doing that until someone asks for it.

I'll close this issue for now since I _believe_ it's solved, but please do let me know if you find that 1.3.0 doesn't fix it :)

Cheers

**Closed as completed by Makeshift** 2023-11-10 11:10 UTC
Labels: bug
